In [1]:
import pandas as pd


file_path = "/kaggle/input/heatwaves/dataset.csv"
df = pd.read_csv(file_path)

df.info(), df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         198 non-null    object
 1   Temperature (°F)             198 non-null    int64
 2   Temperature (°C)             198 non-null    float64
 3   Dew Point (°F)               198 non-null    int64
 4   Dew Point (°C)               198 non-null    float64
 5   Humidity (%)                 198 non-null    int64
 6   Wind Speed (miles per hour)  198 non-null    int64
 7   Event Trigger                198 non-null    int64
dtypes: float64(2), int64(5), object(1)
memory usage: 12.5+ KB

(None,
        Time  Temperature (°F)  Temperature (°C)  Dew Point (°F)  \
 0  12:00 AM                85              29.4              76
 1   1:00 AM                85              29.4              76
 2   2:00 AM                84              28.9              75
 3   3:00 AM                83              28.3              75
 4   4:00 AM                83              28.3              75

    Dew Point (°C)  Humidity (%)  Wind Speed (miles per hour)  Event Trigger
 0            24.4            74                            6              0
 1            24.4            74                            5              0
 2            23.9            74                            8              0
 3            23.9            77                            5              0
 4            23.9            77                            7              0  )

In [2]:
df.head(10)

,Time,Temperature (°F),Temperature (°C),Dew Point (°F),Dew Point (°C),Humidity (%),Wind Speed (miles per hour),Event Trigger
0,12:00 AM,85,29.4,76,24.4,74,6,0
1,1:00 AM,85,29.4,76,24.4,74,5,0
2,2:00 AM,84,28.9,75,23.9,74,8,0
3,3:00 AM,83,28.3,75,23.9,77,5,0
4,4:00 AM,83,28.3,75,23.9,77,7,0
5,5:00 AM,83,28.3,75,23.9,77,8,0
6,6:00 AM,84,28.9,75,23.9,74,7,0
7,7:00 AM,88,31.1,76,24.4,67,9,1
8,8:00 AM,91,32.8,76,24.4,61,9,1
9,9:00 AM,94,34.4,76,24.4,56,10,0

In [3]:
df_cleaned = df[['Temperature (°C)', 'Humidity (%)', 'Event Trigger']]

df_cleaned.isnull().sum()

Temperature (°C)    0
Humidity (%)        0
Event Trigger       0
dtype: int64

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X = df_cleaned[['Temperature (°C)', 'Humidity (%)']]
y = df_cleaned['Event Trigger']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier(max_depth=4) 
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

1.0

In [5]:
test_temperature = 55.5  
test_humidity = 70       


test_input = pd.DataFrame([[test_temperature, test_humidity]], columns=['Temperature (°C)', 'Humidity (%)'])


prediction = model.predict(test_input)


print("Event Triggered" if prediction[0] == 1 else "No Event Triggered")

Event Triggered

In [7]:
import joblib

joblib.dump(model, "model.pkl")

['model.pkl']

In [8]:
model = joblib.load("model.pkl")

In [9]:
from sklearn.tree import export_text

tree_rules = export_text(model, feature_names=["Temperature (°C)'", "Humidity (%)"])
print(tree_rules)

|--- Humidity (%) <= 59.50
|   |--- class: 0
|--- Humidity (%) >  59.50
|   |--- Temperature (°C)' <= 29.70
|   |   |--- class: 0
|   |--- Temperature (°C)' >  29.70
|   |   |--- class: 1